// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI.Context;

#nullable disable

namespace MinimalAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalAPI.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Jrr. Tolkien",
                            Available = true,
                            Genre = "Fantasy",
                            ReleaseYear = 1954,
                            Title = "Lord Of The Rings"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Marcel Proust",
                            Available = true,
                            Genre = "Fiction",
                            ReleaseYear = 1913,
                            Title = "In Search Of Lost Time"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Graham Hancock",
                            Available = false,
                            Genre = "Pseudoarcheology",
                            ReleaseYear = 1995,
                            Title = "Fingerprints Of the Gods"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Richard Dawkins",
                            Available = true,
                            Genre = "Fact",
                            ReleaseYear = 1995,
                            Title = "The God Delusion"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Unknown / King James Bible",
                            Available = true,
                            Genre = "Religious Text",
                            ReleaseYear = 0,
                            Title = "The Holy Bible"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
